import Link from "next/link";
import { AlertTriangle, ArrowUpRight, Plus } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeading } from "@/components/page-heading";

export default function ManufacturerRecalls() {
  return <AppShell manufacturer><PageHeading eyebrow="Northstar Outdoor Tech" title="Recalls" description="Safety notices issued for registered product units." action={<Link href="/manufacturer/recalls/new" className="inline-flex items-center gap-2 bg-ink px-3.5 py-2.5 text-[10px] font-semibold text-white"><Plus size={13} /> Issue Recall</Link>} />
    <div className="mb-4 flex items-center justify-between"><p className="text-[11px] font-semibold">Active safety notices</p><span className="text-[10px] text-muted">1 active</span></div><Link href="/manufacturer/recalls/recall-hc10-2026" className="block border border-[#e8c3bf] bg-[#fff8f6] p-4 sm:p-5"><div className="flex items-start gap-3"><AlertTriangle size={17} className="mt-0.5 text-urgent" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-[10px] font-bold tracking-[.12em] text-urgent">URGENT</span><span className="text-[10px] text-muted">Issued Oct 9, 2026</span></div><h2 className="mt-2 text-[15px] font-semibold">Battery overheating risk</h2><p className="mt-1 text-[11px] text-muted">HeatCore 10K · 127 registered units affected</p><div className="mt-4 flex items-center justify-between border-t border-[#e8c3bf] pt-3 text-[10px] text-muted"><span>127 current owners identified</span><ArrowUpRight size={13} /></div></div></div></Link><div className="mt-8 border-t border-line pt-5"><p className="eyebrow">Safety publication</p><p className="mt-2 text-[12px] leading-5 text-muted">Recall notices are attached to affected product records so current owners can find required actions.</p></div></AppShell>;
}
