import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowUpRight, Plus } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeading } from "@/components/page-heading";
import { ProductArt } from "@/components/product-art";
import { primaryProduct, products } from "@/lib/data";

const models: Record<string, { name: string; category: string; units: number; image: string }> = { HC10: { name: "HeatCore 10K", category: "Portable battery pack", units: 184, image: "/products/heatcore.svg" }, TR4: { name: "TrailRadio 4", category: "Outdoor electronics", units: 51, image: "/products/trailradio.svg" }, FC7: { name: "FieldCharge 7", category: "Portable charger", units: 51, image: "/products/fieldcharge.svg" } };

export default async function ProductModelPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const model = models[id.toUpperCase()]; if (!model) notFound();
  return <AppShell manufacturer><PageHeading eyebrow="Product model · Northstar Outdoor Tech" title={model.name} description={model.category} action={<Link href="/manufacturer/register" className="inline-flex items-center gap-2 bg-ink px-3.5 py-2.5 text-[10px] font-semibold text-white"><Plus size={13} /> Register Unit</Link>} />
    <div className="grid gap-5 lg:grid-cols-[220px_1fr]"><ProductArt src={model.image} alt={model.name} className="aspect-[1.4/1] border border-line bg-[#eeede8] lg:aspect-square" /><div className="grid border border-line sm:grid-cols-3"><div className="border-b border-line p-4 sm:border-b-0 sm:border-r"><p className="eyebrow">Model number</p><p className="mono mt-3 text-[14px]">{id.toUpperCase()}</p></div><div className="border-b border-line p-4 sm:border-b-0 sm:border-r"><p className="eyebrow">Registered units</p><p className="mt-3 text-[22px] font-semibold">{model.units}</p></div><div className="p-4"><p className="eyebrow">Active recalls</p><p className={`mt-3 text-[12px] font-semibold ${id.toUpperCase() === "HC10" ? "text-urgent" : "text-safe"}`}>{id.toUpperCase() === "HC10" ? "1 · Urgent" : "0"}</p></div></div></div>
    <div className="mt-9 flex items-end justify-between border-b border-line pb-3"><div><p className="eyebrow">Unit registry</p><h2 className="mt-1 text-[17px] font-semibold">Registered units</h2></div><span className="text-[10px] text-muted">Sample local records</span></div><div className="mt-3 border border-line">{products.filter((item) => item.model === id.toUpperCase()).map((unit) => <Link key={unit.id} href={`/manufacturer/units/${unit.id}`} className="grid grid-cols-[1fr_auto] items-center gap-3 border-b border-line px-4 py-4 last:border-0 hover:bg-[#f8f7f3] sm:grid-cols-[1fr_1fr_140px_20px]"><div><p className="mono text-[11px] font-semibold">{unit.serial}</p><p className="mt-1 text-[10px] text-muted">{unit.owner === "You" ? "Registered owner" : `Current owner · ${unit.owner}`}</p></div><p className="hidden text-[10px] text-muted sm:block">Registered Oct 1, 2026</p><p className={`text-right text-[10px] font-semibold ${unit.safety === "recalled" ? "text-urgent" : "text-safe"}`}>{unit.safety === "recalled" ? "Urgent recall" : "No active recalls"}</p><ArrowUpRight size={13} className="hidden text-muted sm:block" /></Link>)}{id.toUpperCase() === "HC10" && <div className="border-t border-line px-4 py-3 text-[10px] text-muted">+ 183 additional registered units in this local model preview</div>}</div><p className="sr-only">Example unit: {primaryProduct.serial}</p></AppShell>;
}
