import Link from "next/link";
import { ArrowRight, ArrowUpRight, Boxes, Package, Plus } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { products } from "@/lib/data";

export default function ManufacturerHome() {
  const productModels = ["HeatCore 10K", "TrailRadio 4", "FieldCharge 7"];
  return <AppShell manufacturer title="Products"><div className="mb-7 flex flex-col justify-between gap-3 border-b border-line pb-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Manufacturer workspace · Northstar Outdoor Tech</p><h1 className="mt-2 text-[28px] font-semibold tracking-[-.05em]">Product records</h1><p className="mt-1.5 text-[12px] text-muted">Units, product passports, and active safety notices.</p></div><Link href="/manufacturer/register" className="inline-flex h-10 items-center justify-center gap-2 bg-ink px-4 text-[11px] font-semibold text-white"><Plus size={14} /> Register Product</Link></div>
    <div className="grid border border-line sm:grid-cols-3"><div className="border-b border-line p-4 sm:border-b-0 sm:border-r"><p className="eyebrow">Registered units</p><p className="mt-3 text-[27px] font-semibold tracking-[-.05em]">286</p><p className="mt-1 text-[10px] text-muted">Across 3 product models</p></div><div className="border-b border-line p-4 sm:border-b-0 sm:border-r"><p className="eyebrow">Active recalls</p><p className="mt-3 text-[27px] font-semibold tracking-[-.05em]">1</p><p className="mt-1 text-[10px] text-muted">HeatCore 10K · urgent</p></div><div className="p-4"><p className="eyebrow">Current owners reached</p><p className="mt-3 text-[27px] font-semibold tracking-[-.05em]">127</p><p className="mt-1 text-[10px] text-muted">Affected owners identified</p></div></div>
    <div className="mb-3 mt-9 flex items-end justify-between"><div><p className="eyebrow">Product models</p><h2 className="mt-1 text-[18px] font-semibold tracking-[-.03em]">Your registered range</h2></div><Link href="/manufacturer/products" className="text-[10px] font-semibold underline underline-offset-4">View all products</Link></div><div className="border border-line">{productModels.map((name,index)=><Link href={`/manufacturer/products/${index === 0 ? "HC10" : index === 1 ? "TR4" : "FC7"}`} key={name} className="grid grid-cols-[28px_1fr_auto] items-center gap-3 border-b border-line px-4 py-4 last:border-0 hover:bg-[#f8f7f3]"><Package size={16} className="text-muted" /><div><p className="text-[12px] font-semibold">{name}</p><p className="mt-1 text-[10px] text-muted">{index === 0 ? "Portable battery pack · HC10" : index === 1 ? "Outdoor electronics · TR4" : "Portable charger · FC7"}</p></div><span className="flex items-center gap-2 text-[10px] text-muted">{index === 0 ? "82 units" : "51 units"}<ArrowUpRight size={13} /></span></Link>)}</div>
    <div className="mt-9 flex flex-col justify-between gap-4 border-t border-line pt-6 sm:flex-row sm:items-center"><div><p className="eyebrow">Safety management</p><p className="mt-1 text-[13px] font-semibold">An urgent recall is active for HeatCore 10K.</p><p className="mt-1 text-[11px] text-muted">127 registered product units are in scope.</p></div><Link href="/manufacturer/recalls/recall-hc10-2026" className="inline-flex items-center gap-2 border border-line px-3.5 py-2.5 text-[11px] font-semibold">Review active recall <ArrowRight size={13} /></Link></div>
    <div className="mt-8 flex items-center gap-2 text-[10px] text-muted"><Boxes size={14} />Showing {products.length} local sample product units.</div></AppShell>;
}
